### ISSUE TITLE
Compile Error in MacOS High Sierra

### ISSUE THREAD

**Issue by iPsych** [labstreaminglayer/App-TobiiPro#1]
In high sierra, LLVM 10.0.0 (Xcode 10.0) The compile error happens in below two lines.

error: expected namespace
      name
using namespace std::chrono_literals;

error: invalid suffix 's'
      on integer constant
        std::this_thread::sleep_for(2s);

Change CXX flag in CMakeCache.txt 
from
CMAKE_CXX_FLAGS:STRING=
to 
CMAKE_CXX_FLAGS:STRING=-std=c++1z

Resolve the issue.

**Comment by tstenner** [comment]
> CMAKE_CXX_FLAGS:STRING=-std=c++1z

Good thinking, but `chrono_literals` were introduced in C++14 (so C++17 isn't needed), also no compiler (other than clang++ and g++) will understand `-std=c++1z`.

I've pushed some changes that should append the needed compiler flags, please let me know if it works for you.

**Comment by cboulay** [comment]
Closing as stale.
