### ISSUE TITLE
LSL connector for Glasses 3 Tobii Pro eye tracker available

### ISSUE THREAD

**Issue by esdomar** [labstreaminglayer/App-TobiiPro#3]
I am contacting you from Tobii to let you know that we have recently released an LSL app for our Glasses 3 eye tracker. it is stored here:
https://github.com/tobiipro/Tobii.Glasses3.SDK and includes also a precompiled binary version for windows. What is the procedure to include the G3 app into your LSL app repository and include it in the LSL supported devices documentation?

Estefania.

**Comment by cboulay** [comment]
I'm sorry that no one commented on this until now.
I hope none of your customers were struggling with this. I've updated the readthedocs to include it (should appear online shortly) and I've updated the README here.

Thank you!!
