### ISSUE TITLE
CMake error: C language not enabled

### ISSUE THREAD

**Issue by lawhead** [labstreaminglayer/App-TobiiPro#5]
When building App-TobiiPro from source I encountered a CMake error that the C language is not enabled. This occurred while trying to compile the `arch.c` file provided by [LSL](https://github.com/sccn/liblsl/blob/75119daae8d91d9c5ec22f4c15b5175993dc0a13/cmake/LSLCMake.cmake#L40).

This is fixed by modifying the `project` command in `CMakeLists.txt`:
```
project(TobiiPro
	LANGUAGES C CXX
	VERSION 1.13.0)
```

However, I'm new to CMake so maybe there is a better way to provide the dependency more directly, since I already have the released artifact (liblsl.1.16.0.dylib).

---
For reference, the command executed was:

> $ /usr/local/bin/cmake --no-warn-unused-cli -DLSL_DIR=<path_to_LSL>/liblsl-1.16.0-OSX_amd64/lib/cmake/LSL -DQt5_DIR=<path_to_Qt>/5.15.2/clang_64/lib/cmake/Qt5 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=/usr/local/bin/gcc-11 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/local/bin/g++-11 -S<path_to_tobii-pro>/App-TobiiPro -B<path_to_tobii-pro>/App-TobiiPro/build -G "Unix Makefiles"

And the error was:

> [cmake] CMake Error at <path_to_LSL>/LSL/liblsl-1.16.0-OSX_amd64/lib/cmake/LSL/LSLCMake.cmake:40 (try_compile):
[cmake]   Unknown extension ".c" for file
[cmake]
[cmake]     <path_to_source>/App-TobiiPro/build/arch.c
[cmake]
[cmake]   try_compile() works only for enabled languages.  Currently these are:
[cmake]
[cmake]     CXX
[cmake]
[cmake]   See project() command to enable other languages.
[cmake] Call Stack (most recent call first):
[cmake]   <path_to_LSL>/liblsl-1.16.0-OSX_amd64/lib/cmake/LSL/LSLCMake.cmake:281 (LSL_get_target_arch)
[cmake]   CMakeLists.txt:58 (LSLGenerateCPackConfig)

**Comment by tstenner** [comment]
That's an unfortunate side effect of the CPU architecture detection code. Could you add `enable_language(C)` in the liblsl `LSLCMake.cmake` (immediately before the `try_compile`) and see if it works without changing this project's `CMakeLists.txt`?

**Comment by lawhead** [comment]
@tstenner, adding the `enable_language(C)` in the liblsl `LSLCMake.cmake` file worked for me and the app compiled correctly. It makes sense to add it there since it is a requirement of LSL but not this app.
