### ISSUE TITLE
Stream Metadata for Content Type

### ISSUE THREAD

**Issue by lawhead** [labstreaminglayer/App-TobiiPro#6]
https://github.com/labstreaminglayer/App-TobiiPro/blob/3717265b47c24fa5cbf1e531542182f201999df4/mainwindow.cpp#L138

According to the [LSL documentation](https://github.com/sccn/xdf/wiki/Meta-Data), the content type for eye trackers should be "Gaze". It is currently listed as "Eyetracker".

**Comment by tstenner** [comment]
You're right, I just corrected it. Thanks for reporting this inconsistency.
