### ISSUE TITLE
Cannot successfully compile on Windows 10

### ISSUE THREAD

**Issue by vahid-sb** [labstreaminglayer/App-TobiiPro#7]
Hi
Firstly, thanks for your time and energy to develop this library. I have been trying to compile the code on a Windows 10 PC, using Visual Studio 2022, and so far not been able to compile it. I have the Tobii Pro C SDK and tried to follow the instructions in [LSL Application build instructions](https://labstreaminglayer.readthedocs.io/dev/app_build.html), but the problem is that I do not know the exact options/flags applicable to this specific library. If somebody has a sample of the altered CMakeList.txt or just the executable for a windows 10 machine and could share, it would be much appreciated. 
Vahid

**Comment by lawhead** [comment]
@vahid-sb, I wrote some installation instructions for our group that may be helpful: https://bcipy.github.io/TobiiProInstallation/

Otherwise, there is a slightly modified fork of the project that has created a release with a Windows executable: https://github.com/mfanourakis/App-TobiiPro/releases/tag/V0.9

**Comment by vahid-sb** [comment]
@lawhead thanks a lot for your help. I tried the forked repo and the exe file works, although it crashed a couple of times. And I will look into the installaiton manual you have written too. Have you also written something about the usage of the code? I ask this cause I just did a test recording with a Tobii X3-120 series, for 60 s. Looking at the resulting xdf file, three issues popped into my head.
1. I expected to see 7200 rows but I see 6000, even though I have set the rate at 120 in TobiiPro Connector. 
2. The time Series in the resulting xdf has 8 columns, but I don't know what each one represent, compared to what one gets while recording in Tobii Pro Lab.
3. And also, how to do calibration in this setup? Should I do it using Pro Lab and later on correct x-y values?

Anyway, if you think I can be of help to improve this code, I'd be happy to. This is something that is driectly relevant to my current project and I'd be happy if I can resolve it for my own purposes and also help others who face the same issues along the way.

**Comment by lawhead** [comment]
We have done some initial testing with the Tobii Pro Nano but have not yet documented usage. We use custom Python libraries for data collection and our numbers have come out as expected, so maybe someone else can comment on xdf (and LabRecorder?). We are using the calibration software provided by Tobii.

The 8 columns are "device_ts", "system_ts", "left_x", "left_y", "left_pupil", "right_x" , "right_y", "right_pupil". This is in the LabStreamingLayer metadata.

**Comment by vahid-sb** [comment]
@lawhead thanks for the info. It was quite helpful. 
Regarding, claibration, is there an easy way to incorporate the calibration accuracy data into the gaze behaviour recorded on LSL? Prior to thie project, I solely used Tobii Pro Lab which takes cares of it automatically.
